### ISSUE TITLE
Windows 10, Lens 5.0.0-20210629.3 shows Incompatible in status

### ISSUE THREAD

**Issue by ahriman-ru** [kubecost/kubecost-lens-extension#2]
Tried to install using tgz, no luck. Kubecost is working.

![Capture](https://user-images.githubusercontent.com/11914612/124758301-19901380-df37-11eb-8ae7-136cdfe07762.PNG)

**Comment by AjayTripathy** [comment]
We don't currently support lens 5 in this extension yet...stay tuned for support here!

**Comment by elenalape** [comment]
Hey @ahriman-ru, just wanted to follow up with you — the extension just got an upgrade! It is now compatible with Lens v5.
Please let me know if you run into any issues using the new version https://github.com/kubecost/kubecost-lens-extension/releases/tag/v0.0.3
