### ISSUE TITLE
5.2.3-latest.20210921.1 - Extension shows "Incompatible"

### ISSUE THREAD

**Issue by boscloud** [kubecost/kubecost-lens-extension#3]
![2021-09-21_15-32-49](https://user-images.githubusercontent.com/13108289/134235849-36fddb04-03a7-4c1a-a8ce-0329e57bb80e.png)

**Comment by dwbrown2** [comment]
@boscloud thanks for reporting. I believe this would be the same as issue https://github.com/kubecost/kubecost-lens-extension/issues/2. 

We're talking with the Lens team about a number of big potential improvements here, including Lens 5 support.

**Comment by elenalape** [comment]
Hey @boscloud, a Lens v5 compatible version of the Kubecost extension has just been released!
The upgrade should solve the problem you're seeing. Please let me know if you run into any issues using the extension. https://github.com/kubecost/kubecost-lens-extension/releases/tag/v0.0.3
